// ================================================================
// firestore.js — Sandesh Finance
// All Firestore database read/write functions.
//
// DATABASE STRUCTURE
// ──────────────────
// users/{userId}/
//   ├── investors/{investorId}      — investor documents
//   ├── borrowers/{borrowerId}      — borrower documents
//   ├── loans/{loanId}              — loan documents
//   ├── notifications/{notifId}     — notification documents
//   └── meta/appMeta                — totalCommissionEarned, dismissedAlerts
//
// Every function requires a `userId` param (from getCurrentUser().uid).
// No data is ever written outside the authenticated user's subtree.
// ================================================================

import {
    collection,
    doc,
    addDoc,
    getDoc,
    getDocs,
    setDoc,
    updateDoc,
    deleteDoc,
    query,
    where,
    orderBy,
    serverTimestamp,
    writeBatch,
    increment,
    Timestamp
} from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

import { db } from "./firebase-config.js";

// ================================================================
// COLLECTION PATH HELPERS
// Centralised so paths never drift across functions.
// ================================================================

const col  = (userId, sub)      => collection(db, "users", userId, sub);
const ref  = (userId, sub, id)  => doc(db, "users", userId, sub, id);
const meta = (userId)           => doc(db, "users", userId, "meta", "appMeta");


// ================================================================
//  ██╗███╗   ██╗██╗   ██╗███████╗███████╗████████╗ ██████╗ ██████╗ ███████╗
//  ██║████╗  ██║██║   ██║██╔════╝██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗██╔════╝
//  ██║██╔██╗ ██║██║   ██║█████╗  ███████╗   ██║   ██║   ██║██████╔╝███████╗
//  ██║██║╚██╗██║╚██╗ ██╔╝██╔══╝  ╚════██║   ██║   ██║   ██║██╔══██╗╚════██║
//  ██║██║ ╚████║ ╚████╔╝ ███████╗███████║   ██║   ╚██████╔╝██║  ██║███████║
//  ╚═╝╚═╝  ╚═══╝  ╚═══╝  ╚══════╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝
// ================================================================

/**
 * addInvestor(userId, investorData)
 *
 * Writes a new investor document under users/{userId}/investors.
 * The document ID is auto-generated by Firestore.
 *
 * @param {string} userId        — from auth.getCurrentUser().uid
 * @param {Object} investorData  — shape must match:
 *   {
 *     name:        string,   // full name
 *     phone:       string,   // 10-digit
 *     capital:     number,   // total capital available (₹)
 *     invested:    number,   // currently deployed (default 0)
 *     activeLoans: number    // count of active loans (default 0)
 *   }
 *
 * @returns {Promise<string>}   — the new Firestore document ID
 *
 * EXAMPLE
 *   const id = await addInvestor(uid, { name:"Ravi", phone:"9876543210", capital:500000, invested:0, activeLoans:0 });
 */
export async function addInvestor(userId, investorData) {
    try {
        const payload = {
            name:        investorData.name.trim(),
            phone:       investorData.phone.trim(),
            capital:     Number(investorData.capital),
            invested:    Number(investorData.invested    ?? 0),
            activeLoans: Number(investorData.activeLoans ?? 0),
            createdAt:   serverTimestamp()
        };

        const docRef = await addDoc(col(userId, "investors"), payload);
        console.log("✅ addInvestor →", docRef.id);
        return docRef.id;
    } catch (err) {
        console.error("❌ addInvestor:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * getInvestors(userId)
 *
 * Fetches all investors for this user, ordered by creation time.
 * Returns an array of plain objects with an added `id` field.
 *
 * @returns {Promise<Array<{id:string, name:string, phone:string,
 *                          capital:number, invested:number, activeLoans:number}>>}
 *
 * EXAMPLE
 *   const investors = await getInvestors(uid);
 *   appData.investors = investors;
 *   renderInvestors();
 */
export async function getInvestors(userId) {
    try {
        const q        = query(col(userId, "investors"), orderBy("createdAt", "asc"));
        const snapshot = await getDocs(q);

        const investors = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
        console.log(`✅ getInvestors → ${investors.length} records`);
        return investors;
    } catch (err) {
        console.error("❌ getInvestors:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * updateInvestor(userId, investorId, updates)
 *
 * Partial update — only the fields you pass are changed.
 * Useful for updating capital, invested amount, or activeLoans count
 * after a loan is created or completed.
 *
 * @param {Object} updates  — e.g. { invested: 150000, activeLoans: 2 }
 *
 * EXAMPLE — after a loan is created:
 *   await updateInvestor(uid, investorId, {
 *       invested:    increment(loanAmount),  // use Firestore increment() helper
 *       activeLoans: increment(1)
 *   });
 *
 * NOTE: import { increment } from firebase-firestore to use atomic increments.
 */
export async function updateInvestor(userId, investorId, updates) {
    try {
        await updateDoc(ref(userId, "investors", investorId), {
            ...updates,
            updatedAt: serverTimestamp()
        });
        console.log("✅ updateInvestor →", investorId);
    } catch (err) {
        console.error("❌ updateInvestor:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * deleteInvestor(userId, investorId)
 *
 * Deletes an investor document.
 * ⚠ GUARD: Call getLoans() first and refuse if any active loan
 *           references this investorId (mirrors existing app behaviour).
 *
 * EXAMPLE
 *   const loans = await getLoans(uid);
 *   if (loans.some(l => l.investorId === id && l.status === 'active')) {
 *       showToast('Has active loans', 'error');
 *       return;
 *   }
 *   await deleteInvestor(uid, id);
 */
export async function deleteInvestor(userId, investorId) {
    try {
        await deleteDoc(ref(userId, "investors", investorId));
        console.log("✅ deleteInvestor →", investorId);
    } catch (err) {
        console.error("❌ deleteInvestor:", err);
        throw err;
    }
}


// ================================================================
//  ██████╗  ██████╗ ██████╗ ██████╗  ██████╗ ██╗    ██╗███████╗██████╗ ███████╗
//  ██╔══██╗██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║    ██║██╔════╝██╔══██╗██╔════╝
//  ██████╔╝██║   ██║██████╔╝██████╔╝██║   ██║██║ █╗ ██║█████╗  ██████╔╝███████╗
//  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██║   ██║██║███╗██║██╔══╝  ██╔══██╗╚════██║
//  ██████╔╝╚██████╔╝██║  ██║██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║███████║
//  ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚══════╝
// ================================================================

/**
 * addBorrower(userId, borrowerData)
 *
 * @param {Object} borrowerData — shape:
 *   {
 *     name:        string,
 *     phone:       string,
 *     address:     string,   // optional
 *     borrowed:    number,   // default 0
 *     activeLoans: number    // default 0
 *   }
 *
 * @returns {Promise<string>}  — new document ID
 */
export async function addBorrower(userId, borrowerData) {
    try {
        const payload = {
            name:        borrowerData.name.trim(),
            phone:       borrowerData.phone.trim(),
            address:     (borrowerData.address || "").trim(),
            borrowed:    Number(borrowerData.borrowed    ?? 0),
            activeLoans: Number(borrowerData.activeLoans ?? 0),
            createdAt:   serverTimestamp()
        };

        const docRef = await addDoc(col(userId, "borrowers"), payload);
        console.log("✅ addBorrower →", docRef.id);
        return docRef.id;
    } catch (err) {
        console.error("❌ addBorrower:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * getBorrowers(userId)
 *
 * @returns {Promise<Array<{id:string, name:string, phone:string,
 *                          address:string, borrowed:number, activeLoans:number}>>}
 */
export async function getBorrowers(userId) {
    try {
        const q        = query(col(userId, "borrowers"), orderBy("createdAt", "asc"));
        const snapshot = await getDocs(q);

        const borrowers = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
        console.log(`✅ getBorrowers → ${borrowers.length} records`);
        return borrowers;
    } catch (err) {
        console.error("❌ getBorrowers:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * updateBorrower(userId, borrowerId, updates)
 *
 * Partial update for borrower fields (borrowed amount, activeLoans, etc.)
 */
export async function updateBorrower(userId, borrowerId, updates) {
    try {
        await updateDoc(ref(userId, "borrowers", borrowerId), {
            ...updates,
            updatedAt: serverTimestamp()
        });
        console.log("✅ updateBorrower →", borrowerId);
    } catch (err) {
        console.error("❌ updateBorrower:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * deleteBorrower(userId, borrowerId)
 *
 * ⚠ GUARD: Check for active loans before calling — same as deleteInvestor.
 */
export async function deleteBorrower(userId, borrowerId) {
    try {
        await deleteDoc(ref(userId, "borrowers", borrowerId));
        console.log("✅ deleteBorrower →", borrowerId);
    } catch (err) {
        console.error("❌ deleteBorrower:", err);
        throw err;
    }
}


// ================================================================
//  ██╗      ██████╗  █████╗ ███╗   ██╗███████╗
//  ██║     ██╔═══██╗██╔══██╗████╗  ██║██╔════╝
//  ██║     ██║   ██║███████║██╔██╗ ██║███████╗
//  ██║     ██║   ██║██╔══██║██║╚██╗██║╚════██║
//  ███████╗╚██████╔╝██║  ██║██║ ╚████║███████║
//  ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝
// ================================================================

/**
 * addLoan(userId, loanData)
 *
 * Writes the loan document AND atomically updates the referenced
 * investor and borrower counters in a single Firestore batch —
 * ensuring data stays consistent even if the browser closes mid-way.
 *
 * @param {Object} loanData — full shape from loanForm submit:
 *   {
 *     investorId:       string,
 *     borrowerId:       string,
 *     investorName:     string,
 *     borrowerName:     string,
 *     amount:           number,
 *     borrowerRate:     number,   // % the borrower pays
 *     investorRate:     number,   // % the investor earns
 *     frequency:        string,   // 'daily'|'weekly'|'15days'|'monthly'|'yearly'
 *     duration:         number,
 *     durationUnit:     string,   // 'days'|'weeks'|'months'|'years'
 *     durationInMonths: number,
 *     startDate:        string,   // "YYYY-MM-DD"
 *     dueDate:          string,   // "YYYY-MM-DD" — calculated before calling
 *     totalInterest:    number,
 *     investorShare:    number,
 *     commissionAmount: number,
 *     totalPayable:     number,
 *     status:           'active'
 *   }
 *
 * @returns {Promise<string>}  — new loan document ID
 */
export async function addLoan(userId, loanData) {
    try {
        const batch     = writeBatch(db);

        // 1 — Loan document (new auto-ID doc)
        const loanDocRef = doc(col(userId, "loans"));
        batch.set(loanDocRef, {
            investorId:       loanData.investorId,
            borrowerId:       loanData.borrowerId,
            investorName:     loanData.investorName,
            borrowerName:     loanData.borrowerName,
            amount:           Number(loanData.amount),
            borrowerRate:     Number(loanData.borrowerRate),
            investorRate:     Number(loanData.investorRate),
            frequency:        loanData.frequency,
            duration:         Number(loanData.duration),
            durationUnit:     loanData.durationUnit,
            durationInMonths: Number(loanData.durationInMonths),
            startDate:        loanData.startDate,
            dueDate:          loanData.dueDate,
            totalInterest:    Number(loanData.totalInterest),
            investorShare:    Number(loanData.investorShare),
            commissionAmount: Number(loanData.commissionAmount),
            totalPayable:     Number(loanData.totalPayable),
            status:           "active",
            delays:           [],          // populated by addLoanDelay()
            createdAt:        serverTimestamp()
        });

        // 2 — Update investor: increase invested + activeLoans counter
        batch.update(ref(userId, "investors", loanData.investorId), {
            invested:    increment(Number(loanData.amount)),
            activeLoans: increment(1),
            updatedAt:   serverTimestamp()
        });

        // 3 — Update borrower: increase borrowed + activeLoans counter
        batch.update(ref(userId, "borrowers", loanData.borrowerId), {
            borrowed:    increment(Number(loanData.amount)),
            activeLoans: increment(1),
            updatedAt:   serverTimestamp()
        });

        await batch.commit();
        console.log("✅ addLoan →", loanDocRef.id);
        return loanDocRef.id;
    } catch (err) {
        console.error("❌ addLoan:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * getLoans(userId, statusFilter?)
 *
 * Fetches all loan documents for this user.
 * Pass statusFilter = 'active' | 'completed' to narrow results.
 *
 * @param {string} [statusFilter]  — optional Firestore where() filter
 * @returns {Promise<Array>}
 *
 * EXAMPLE
 *   const allLoans    = await getLoans(uid);
 *   const activeLoans = await getLoans(uid, 'active');
 */
export async function getLoans(userId, statusFilter = null) {
    try {
        let q;
        if (statusFilter) {
            q = query(
                col(userId, "loans"),
                where("status", "==", statusFilter),
                orderBy("createdAt", "asc")
            );
        } else {
            q = query(col(userId, "loans"), orderBy("createdAt", "asc"));
        }

        const snapshot = await getDocs(q);
        const loans    = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
        console.log(`✅ getLoans (${statusFilter ?? "all"}) → ${loans.length} records`);
        return loans;
    } catch (err) {
        console.error("❌ getLoans:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * updateLoanStatus(userId, loanId, newStatus)
 *
 * Marks a loan as 'completed' or 'defaulted' and atomically
 * reverses the investor/borrower counters in the same batch.
 * Also increments totalCommissionEarned on the meta document.
 *
 * @param {string} newStatus  — 'completed' | 'defaulted'
 *
 * EXAMPLE
 *   await updateLoanStatus(uid, loanId, 'completed');
 */
export async function updateLoanStatus(userId, loanId, newStatus) {
    try {
        // Fetch the loan to read amount and commissionAmount
        const loanSnap = await getDoc(ref(userId, "loans", loanId));
        if (!loanSnap.exists()) throw new Error(`Loan ${loanId} not found`);

        const loan  = loanSnap.data();
        const batch = writeBatch(db);

        // 1 — Update loan status
        batch.update(ref(userId, "loans", loanId), {
            status:        newStatus,
            completedDate: new Date().toISOString().split("T")[0],
            updatedAt:     serverTimestamp()
        });

        // 2 — Reverse investor counters
        batch.update(ref(userId, "investors", loan.investorId), {
            invested:    increment(-Number(loan.amount)),
            activeLoans: increment(-1),
            updatedAt:   serverTimestamp()
        });

        // 3 — Reverse borrower counters
        batch.update(ref(userId, "borrowers", loan.borrowerId), {
            borrowed:    increment(-Number(loan.amount)),
            activeLoans: increment(-1),
            updatedAt:   serverTimestamp()
        });

        // 4 — Accumulate commission in meta document (upsert with merge)
        if (newStatus === "completed") {
            batch.set(meta(userId), {
                totalCommissionEarned: increment(Number(loan.commissionAmount ?? 0)),
                updatedAt: serverTimestamp()
            }, { merge: true });
        }

        await batch.commit();
        console.log(`✅ updateLoanStatus → ${loanId} is now ${newStatus}`);
    } catch (err) {
        console.error("❌ updateLoanStatus:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * addLoanDelay(userId, loanId, delayEntry)
 *
 * Appends a delay entry to the loan's delays array and updates
 * the loan's dueDate, durationInMonths, totalPayable, and penalty fields.
 *
 * @param {Object} delayEntry — shape:
 *   {
 *     id:              string,   // generateId()
 *     previousDueDate: string,   // "YYYY-MM-DD"
 *     newDueDate:      string,   // "YYYY-MM-DD"
 *     penaltyAmount:   number,
 *     penaltyFrequency:string,   // 'none'|'daily'|'weekly'|'monthly'
 *     reason:          string,
 *     addedDate:       string    // "YYYY-MM-DD"
 *   }
 */
export async function addLoanDelay(userId, loanId, delayEntry, updatedLoanFields) {
    try {
        // updatedLoanFields: { dueDate, durationInMonths, totalPayable,
        //                      totalInterest, commissionAmount, investorShare }
        await updateDoc(ref(userId, "loans", loanId), {
            delays:    delayEntry,          // use arrayUnion in real call — see note below
            ...updatedLoanFields,
            updatedAt: serverTimestamp()
        });
        // NOTE: Replace `delays: delayEntry` with:
        //   delays: arrayUnion(delayEntry)
        // after importing arrayUnion from firebase-firestore.
        console.log("✅ addLoanDelay →", loanId);
    } catch (err) {
        console.error("❌ addLoanDelay:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * deleteLoan(userId, loanId)
 *
 * Deletes a loan document. If the loan was still 'active', also
 * reverses the investor and borrower counters in a batch.
 *
 * ⚠  Always fetch the loan first to check its status.
 *
 * EXAMPLE
 *   const loan = (await getLoans(uid)).find(l => l.id === loanId);
 *   await deleteLoan(uid, loanId, loan);
 */
export async function deleteLoan(userId, loanId, loanData) {
    try {
        const batch = writeBatch(db);

        // 1 — Delete the loan document
        batch.delete(ref(userId, "loans", loanId));

        // 2 — If it was active, reverse the counters
        if (loanData?.status === "active") {
            batch.update(ref(userId, "investors", loanData.investorId), {
                invested:    increment(-Number(loanData.amount)),
                activeLoans: increment(-1),
                updatedAt:   serverTimestamp()
            });
            batch.update(ref(userId, "borrowers", loanData.borrowerId), {
                borrowed:    increment(-Number(loanData.amount)),
                activeLoans: increment(-1),
                updatedAt:   serverTimestamp()
            });
        }

        await batch.commit();
        console.log("✅ deleteLoan →", loanId);
    } catch (err) {
        console.error("❌ deleteLoan:", err);
        throw err;
    }
}


// ================================================================
//  ███╗   ██╗ ██████╗ ████████╗██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
//  ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██║██╔════╝ ████╗  ██║██╔════╝
//  ██╔██╗ ██║██║   ██║   ██║   ██║█████╗  ██║██║      ██╔██╗ ██║███████╗
//  ██║╚██╗██║██║   ██║   ██║   ██║██╔══╝  ██║██║      ██║╚██╗██║╚════██║
//  ██║ ╚████║╚██████╔╝   ██║   ██║██║     ██║╚██████╗ ██║ ╚████║███████║
//  ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝
// ================================================================

/**
 * Notification document shape:
 * {
 *   type:      string,   // 'loan_due' | 'loan_overdue' | 'loan_completed' | 'new_loan'
 *   title:     string,   // short heading
 *   message:   string,   // full description
 *   loanId:    string,   // related loan (optional)
 *   isRead:    boolean,  // false by default
 *   createdAt: Timestamp
 * }
 */

// ----------------------------------------------------------------

/**
 * addNotification(userId, notifData)
 *
 * Creates a new notification — call this from your app logic
 * whenever a significant event occurs (loan created, loan due soon, etc.)
 *
 * @returns {Promise<string>}  — new document ID
 *
 * EXAMPLE — after creating a loan:
 *   await addNotification(uid, {
 *       type:    'new_loan',
 *       title:   'New Loan Created',
 *       message: `Loan of ₹50,000 to Ramesh Kumar (via Investor: Ravi)`,
 *       loanId:  newLoanId
 *   });
 */
export async function addNotification(userId, notifData) {
    try {
        const payload = {
            type:      notifData.type    ?? "general",
            title:     notifData.title   ?? "",
            message:   notifData.message ?? "",
            loanId:    notifData.loanId  ?? null,
            isRead:    false,
            createdAt: serverTimestamp()
        };

        const docRef = await addDoc(col(userId, "notifications"), payload);
        console.log("✅ addNotification →", docRef.id);
        return docRef.id;
    } catch (err) {
        console.error("❌ addNotification:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * getNotifications(userId, unreadOnly?)
 *
 * Fetches notifications for this user, newest first.
 * Pass unreadOnly = true to fetch only unread notifications
 * (useful for the notification badge count).
 *
 * @param {boolean} [unreadOnly=false]
 * @returns {Promise<Array>}
 *
 * EXAMPLE
 *   const all    = await getNotifications(uid);
 *   const unread = await getNotifications(uid, true);
 *   document.getElementById('notifBadge').textContent = unread.length;
 */
export async function getNotifications(userId, unreadOnly = false) {
    try {
        let q;
        if (unreadOnly) {
            q = query(
                col(userId, "notifications"),
                where("isRead", "==", false),
                orderBy("createdAt", "desc")
            );
        } else {
            q = query(
                col(userId, "notifications"),
                orderBy("createdAt", "desc")
            );
        }

        const snapshot      = await getDocs(q);
        const notifications = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
        console.log(`✅ getNotifications (unreadOnly=${unreadOnly}) → ${notifications.length}`);
        return notifications;
    } catch (err) {
        console.error("❌ getNotifications:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * markNotificationRead(userId, notifId)
 *
 * Sets isRead = true on a single notification document.
 *
 * EXAMPLE — when user clicks a notification:
 *   await markNotificationRead(uid, notif.id);
 *   renderNotifications();  // refresh the list
 */
export async function markNotificationRead(userId, notifId) {
    try {
        await updateDoc(ref(userId, "notifications", notifId), {
            isRead:    true,
            readAt:    serverTimestamp()
        });
        console.log("✅ markNotificationRead →", notifId);
    } catch (err) {
        console.error("❌ markNotificationRead:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * markAllNotificationsRead(userId)
 *
 * Marks every unread notification as read in a single batch.
 * Call when user opens the notifications panel.
 */
export async function markAllNotificationsRead(userId) {
    try {
        const unread = await getNotifications(userId, true);
        if (!unread.length) return;

        const batch = writeBatch(db);
        unread.forEach(n => {
            batch.update(ref(userId, "notifications", n.id), {
                isRead: true,
                readAt: serverTimestamp()
            });
        });

        await batch.commit();
        console.log(`✅ markAllNotificationsRead → ${unread.length} marked`);
    } catch (err) {
        console.error("❌ markAllNotificationsRead:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * deleteNotification(userId, notifId)
 *
 * Removes a single notification document.
 */
export async function deleteNotification(userId, notifId) {
    try {
        await deleteDoc(ref(userId, "notifications", notifId));
        console.log("✅ deleteNotification →", notifId);
    } catch (err) {
        console.error("❌ deleteNotification:", err);
        throw err;
    }
}


// ================================================================
//  META DOCUMENT  (totalCommissionEarned, dismissedAlerts)
// ================================================================

/**
 * getAppMeta(userId)
 *
 * Returns the meta document for this user.
 * Contains: totalCommissionEarned, dismissedAlerts, updatedAt.
 *
 * Returns a safe default object if the document doesn't exist yet.
 *
 * EXAMPLE
 *   const meta = await getAppMeta(uid);
 *   appData.totalCommissionEarned = meta.totalCommissionEarned;
 *   appData.dismissedAlerts       = meta.dismissedAlerts;
 */
export async function getAppMeta(userId) {
    try {
        const snap = await getDoc(meta(userId));
        if (snap.exists()) {
            return snap.data();
        }
        // First-time user — return safe defaults
        return { totalCommissionEarned: 0, dismissedAlerts: {} };
    } catch (err) {
        console.error("❌ getAppMeta:", err);
        throw err;
    }
}

// ----------------------------------------------------------------

/**
 * updateAppMeta(userId, updates)
 *
 * Partial update for the meta document.
 * Uses { merge: true } so new keys don't overwrite the whole doc.
 *
 * EXAMPLE — save dismissed alert keys:
 *   await updateAppMeta(uid, { dismissedAlerts: appData.dismissedAlerts });
 *
 * EXAMPLE — manually set commission total:
 *   await updateAppMeta(uid, { totalCommissionEarned: 250000 });
 */
export async function updateAppMeta(userId, updates) {
    try {
        await setDoc(meta(userId), {
            ...updates,
            updatedAt: serverTimestamp()
        }, { merge: true });
        console.log("✅ updateAppMeta");
    } catch (err) {
        console.error("❌ updateAppMeta:", err);
        throw err;
    }
}


// ================================================================
//  FULL APP BOOTSTRAP — loadAllData(userId)
// ================================================================

/**
 * loadAllData(userId)
 *
 * Fetches all collections in parallel and returns an appData-shaped
 * object that is a drop-in replacement for the existing localStorage
 * appData. Wire this into the DOMContentLoaded block in script.js
 * as part of Step 3 (localStorage → Firestore migration).
 *
 * @returns {Promise<{
 *   investors: Array,
 *   borrowers: Array,
 *   loans:     Array,
 *   totalCommissionEarned: number,
 *   dismissedAlerts: Object,
 *   delays: Array
 * }>}
 *
 * EXAMPLE — replacing loadData() in script.js:
 *
 *   import { loadAllData } from './firestore.js';
 *   import { onAuthChange } from './auth.js';
 *
 *   onAuthChange(async (user) => {
 *       if (!user) { window.location.href = 'login.html'; return; }
 *
 *       appData = await loadAllData(user.uid);
 *       renderInvestors();
 *       renderBorrowers();
 *       renderLoans();
 *       updateStats();
 *       updateCapitalOverview();
 *   });
 */
export async function loadAllData(userId) {
    try {
        const [investors, borrowers, loans, metaDoc] = await Promise.all([
            getInvestors(userId),
            getBorrowers(userId),
            getLoans(userId),
            getAppMeta(userId)
        ]);

        return {
            investors,
            borrowers,
            loans,
            totalCommissionEarned: metaDoc.totalCommissionEarned ?? 0,
            dismissedAlerts:       metaDoc.dismissedAlerts       ?? {},
            delays:                []   // delays are embedded inside each loan document
        };
    } catch (err) {
        console.error("❌ loadAllData:", err);
        throw err;
    }
}


// ================================================================
//  FIRESTORE SECURITY RULES  (paste into Firebase Console)
// ================================================================
//
//  rules_version = '2';
//  service cloud.firestore {
//    match /databases/{database}/documents {
//
//      // Block all access by default
//      match /{document=**} {
//        allow read, write: if false;
//      }
//
//      // Each user can only read/write their own subtree
//      match /users/{userId}/{collection}/{docId} {
//        allow read, write: if request.auth != null
//                           && request.auth.uid == userId;
//      }
//
//      // Meta document same rule
//      match /users/{userId}/meta/{doc} {
//        allow read, write: if request.auth != null
//                           && request.auth.uid == userId;
//      }
//    }
//  }
//
// ================================================================
